# PRCP-1025-FlightPricePrediction

## IMPORT LIBRARIES

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## TASK 1 — DATA ANALYSIS REPORT

In [71]:
df = pd.read_excel("Flight_Fare.xlsx")
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

### Dataset Overview

- Rows: 10,682

- Features: 29

- Target variable: Price

- Problem Type: Regression

#### Price statistics

- Minimum price: ₹1,759

- Maximum price: ₹79,512

- Average price: ₹9,087

In [73]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [74]:
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [76]:
df.isna().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [77]:
df=df.dropna()

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Date_of_Journey  10682 non-null  object
 2   Source           10682 non-null  object
 3   Destination      10682 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10682 non-null  object
 6   Arrival_Time     10682 non-null  object
 7   Duration         10682 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10682 non-null  object
 10  Price            10682 non-null  int64
dtypes: int64(1), object(10)
memory usage: 1001.4+ KB

## PREPROSESSING

In [79]:
df = df.drop(["Route","Additional_Info"],axis=True)

In [80]:
df

,Airline,Date_of_Journey,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,22:20,01:10 22 Mar,2h 50m,non-stop,3897
1,Air India,1/05/2019,Kolkata,Banglore,05:50,13:15,7h 25m,2 stops,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,09:25,04:25 10 Jun,19h,2 stops,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,18:05,23:30,5h 25m,1 stop,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,16:50,21:35,4h 45m,1 stop,13302
...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,19:55,22:25,2h 30m,non-stop,4107
10679,Air India,27/04/2019,Kolkata,Banglore,20:45,23:20,2h 35m,non-stop,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,08:20,11:20,3h,non-stop,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,11:30,14:10,2h 40m,non-stop,12648
10682,Air India,9/05/2019,Delhi,Cochin,10:55,19:15,8h 20m,2 stops,11753

In [81]:
df = pd.get_dummies(df,columns=["Airline","Source","Destination"],drop_first=1)

In [82]:
df

,Date_of_Journey,Dep_Time,Arrival_Time,Duration,Total_Stops,Price,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,...,Airline_Vistara Premium economy,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,24/03/2019,22:20,01:10 22 Mar,2h 50m,non-stop,3897,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
1,1/05/2019,05:50,13:15,7h 25m,2 stops,7662,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
2,9/06/2019,09:25,04:25 10 Jun,19h,2 stops,13882,False,False,False,True,...,False,False,True,False,False,True,False,False,False,False
3,12/05/2019,18:05,23:30,5h 25m,1 stop,6218,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
4,01/03/2019,16:50,21:35,4h 45m,1 stop,13302,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,9/04/2019,19:55,22:25,2h 30m,non-stop,4107,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
10679,27/04/2019,20:45,23:20,2h 35m,non-stop,4145,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
10680,27/04/2019,08:20,11:20,3h,non-stop,7229,False,False,False,True,...,False,False,False,False,False,False,True,False,False,False
10681,01/03/2019,11:30,14:10,2h 40m,non-stop,12648,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
10682,9/05/2019,10:55,19:15,8h 20m,2 stops,11753,True,False,False,False,...,False,False,True,False,False,True,False,False,False,False

In [83]:
df['Total_Stops'].value_counts()

Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
4 stops        1
Name: count, dtype: int64

In [84]:
df["Total_Stops"] = df["Total_Stops"].replace({
    "non-stop":0,
    "1 stop":1,
    "2 stops":2,
    "3 stops":3,
    "4 stops":4
})

C:\Users\aravi\AppData\Local\Temp\ipykernel_19740\1543106999.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Total_Stops"] = df["Total_Stops"].replace({

In [85]:
df

,Date_of_Journey,Dep_Time,Arrival_Time,Duration,Total_Stops,Price,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,...,Airline_Vistara Premium economy,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,24/03/2019,22:20,01:10 22 Mar,2h 50m,0,3897,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
1,1/05/2019,05:50,13:15,7h 25m,2,7662,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
2,9/06/2019,09:25,04:25 10 Jun,19h,2,13882,False,False,False,True,...,False,False,True,False,False,True,False,False,False,False
3,12/05/2019,18:05,23:30,5h 25m,1,6218,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
4,01/03/2019,16:50,21:35,4h 45m,1,13302,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,9/04/2019,19:55,22:25,2h 30m,0,4107,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
10679,27/04/2019,20:45,23:20,2h 35m,0,4145,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
10680,27/04/2019,08:20,11:20,3h,0,7229,False,False,False,True,...,False,False,False,False,False,False,True,False,False,False
10681,01/03/2019,11:30,14:10,2h 40m,0,12648,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
10682,9/05/2019,10:55,19:15,8h 20m,2,11753,True,False,False,False,...,False,False,True,False,False,True,False,False,False,False

In [86]:
df["Journey_Day"] = pd.to_datetime(df["Date_of_Journey"],format = "%d/%m/%Y").dt.day

In [87]:
df["Journey_Month"] = pd.to_datetime(df["Date_of_Journey"],format = "%d/%m/%Y").dt.month

In [88]:
df.drop("Date_of_Journey",axis=1,inplace=True)

In [89]:
df

,Dep_Time,Arrival_Time,Duration,Total_Stops,Price,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,...,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,Journey_Day,Journey_Month
0,22:20,01:10 22 Mar,2h 50m,0,3897,False,False,True,False,False,...,False,False,False,False,False,False,False,True,24,3
1,05:50,13:15,7h 25m,2,7662,True,False,False,False,False,...,False,True,False,False,False,False,False,False,1,5
2,09:25,04:25 10 Jun,19h,2,13882,False,False,False,True,False,...,True,False,False,True,False,False,False,False,9,6
3,18:05,23:30,5h 25m,1,6218,False,False,True,False,False,...,False,True,False,False,False,False,False,False,12,5
4,16:50,21:35,4h 45m,1,13302,False,False,True,False,False,...,False,False,False,False,False,False,False,True,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,19:55,22:25,2h 30m,0,4107,False,False,False,False,False,...,False,True,False,False,False,False,False,False,9,4
10679,20:45,23:20,2h 35m,0,4145,True,False,False,False,False,...,False,True,False,False,False,False,False,False,27,4
10680,08:20,11:20,3h,0,7229,False,False,False,True,False,...,False,False,False,False,True,False,False,False,27,4
10681,11:30,14:10,2h 40m,0,12648,False,False,False,False,False,...,False,False,False,False,False,False,False,True,1,3
10682,10:55,19:15,8h 20m,2,11753,True,False,False,False,False,...,True,False,False,True,False,False,False,False,9,5

In [90]:
df["Dep_Hour"] = pd.to_datetime(df["Dep_Time"]).dt.hour

C:\Users\aravi\AppData\Local\Temp\ipykernel_19740\1331536135.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Dep_Hour"] = pd.to_datetime(df["Dep_Time"]).dt.hour

In [91]:
df["Dep_Minute"] = pd.to_datetime(df["Dep_Time"]).dt.minute

C:\Users\aravi\AppData\Local\Temp\ipykernel_19740\1768342231.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Dep_Minute"] = pd.to_datetime(df["Dep_Time"]).dt.minute

In [96]:
df.drop("Dep_Time",axis=1,inplace=True)

In [97]:
df

,Arrival_Time,Duration,Total_Stops,Price,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,...,Source_Mumbai,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,Journey_Day,Journey_Month,Dep_Hour,Dep_Minute
0,01:10 22 Mar,2h 50m,0,3897,False,False,True,False,False,False,...,False,False,False,False,False,True,24,3,22,20
1,13:15,7h 25m,2,7662,True,False,False,False,False,False,...,False,False,False,False,False,False,1,5,5,50
2,04:25 10 Jun,19h,2,13882,False,False,False,True,False,False,...,False,True,False,False,False,False,9,6,9,25
3,23:30,5h 25m,1,6218,False,False,True,False,False,False,...,False,False,False,False,False,False,12,5,18,5
4,21:35,4h 45m,1,13302,False,False,True,False,False,False,...,False,False,False,False,False,True,1,3,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,22:25,2h 30m,0,4107,False,False,False,False,False,False,...,False,False,False,False,False,False,9,4,19,55
10679,23:20,2h 35m,0,4145,True,False,False,False,False,False,...,False,False,False,False,False,False,27,4,20,45
10680,11:20,3h,0,7229,False,False,False,True,False,False,...,False,False,True,False,False,False,27,4,8,20
10681,14:10,2h 40m,0,12648,False,False,False,False,False,False,...,False,False,False,False,False,True,1,3,11,30
10682,19:15,8h 20m,2,11753,True,False,False,False,False,False,...,False,True,False,False,False,False,9,5,10,55

In [98]:
df["Arrival_Minute"] = pd.to_datetime(df["Arrival_Time"]).dt.minute

C:\Users\aravi\AppData\Local\Temp\ipykernel_19740\3257876746.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Arrival_Minute"] = pd.to_datetime(df["Arrival_Time"]).dt.minute

In [99]:
df["Arrival_Hour"] = pd.to_datetime(df["Arrival_Time"]).dt.hour

C:\Users\aravi\AppData\Local\Temp\ipykernel_19740\1971985902.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Arrival_Hour"] = pd.to_datetime(df["Arrival_Time"]).dt.hour

In [101]:
df.drop("Arrival_Time",axis=1,inplace=True)

In [102]:
df

,Duration,Total_Stops,Price,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,...,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,Journey_Day,Journey_Month,Dep_Hour,Dep_Minute,Arrival_Minute,Arrival_Hour
0,2h 50m,0,3897,False,False,True,False,False,False,False,...,False,False,False,True,24,3,22,20,10,1
1,7h 25m,2,7662,True,False,False,False,False,False,False,...,False,False,False,False,1,5,5,50,15,13
2,19h,2,13882,False,False,False,True,False,False,False,...,False,False,False,False,9,6,9,25,25,4
3,5h 25m,1,6218,False,False,True,False,False,False,False,...,False,False,False,False,12,5,18,5,30,23
4,4h 45m,1,13302,False,False,True,False,False,False,False,...,False,False,False,True,1,3,16,50,35,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,2h 30m,0,4107,False,False,False,False,False,False,False,...,False,False,False,False,9,4,19,55,25,22
10679,2h 35m,0,4145,True,False,False,False,False,False,False,...,False,False,False,False,27,4,20,45,20,23
10680,3h,0,7229,False,False,False,True,False,False,False,...,True,False,False,False,27,4,8,20,20,11
10681,2h 40m,0,12648,False,False,False,False,False,False,False,...,False,False,False,True,1,3,11,30,10,14
10682,8h 20m,2,11753,True,False,False,False,False,False,False,...,False,False,False,False,9,5,10,55,15,19

In [103]:
df["Duration"] = df["Duration"].str.replace("h","*60").str.replace("m","+1").str.replace(" ","")

In [105]:
df["Duration"] = df["Duration"].apply(eval)

In [106]:
df

,Duration,Total_Stops,Price,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,...,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,Journey_Day,Journey_Month,Dep_Hour,Dep_Minute,Arrival_Minute,Arrival_Hour
0,12101,0,3897,False,False,True,False,False,False,False,...,False,False,False,True,24,3,22,20,10,1
1,42176,2,7662,True,False,False,False,False,False,False,...,False,False,False,False,1,5,5,50,15,13
2,1140,2,13882,False,False,False,True,False,False,False,...,False,False,False,False,9,6,9,25,25,4
3,30126,1,6218,False,False,True,False,False,False,False,...,False,False,False,False,12,5,18,5,30,23
4,24181,1,13302,False,False,True,False,False,False,False,...,False,False,False,True,1,3,16,50,35,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,12061,0,4107,False,False,False,False,False,False,False,...,False,False,False,False,9,4,19,55,25,22
10679,12071,0,4145,True,False,False,False,False,False,False,...,False,False,False,False,27,4,20,45,20,23
10680,180,0,7229,False,False,False,True,False,False,False,...,True,False,False,False,27,4,8,20,20,11
10681,12081,0,12648,False,False,False,False,False,False,False,...,False,False,False,True,1,3,11,30,10,14
10682,48161,2,11753,True,False,False,False,False,False,False,...,False,False,False,False,9,5,10,55,15,19

In [109]:
df = df.astype(int)

In [110]:
df

,Duration,Total_Stops,Price,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,...,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,Journey_Day,Journey_Month,Dep_Hour,Dep_Minute,Arrival_Minute,Arrival_Hour
0,12101,0,3897,0,0,1,0,0,0,0,...,0,0,0,1,24,3,22,20,10,1
1,42176,2,7662,1,0,0,0,0,0,0,...,0,0,0,0,1,5,5,50,15,13
2,1140,2,13882,0,0,0,1,0,0,0,...,0,0,0,0,9,6,9,25,25,4
3,30126,1,6218,0,0,1,0,0,0,0,...,0,0,0,0,12,5,18,5,30,23
4,24181,1,13302,0,0,1,0,0,0,0,...,0,0,0,1,1,3,16,50,35,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,12061,0,4107,0,0,0,0,0,0,0,...,0,0,0,0,9,4,19,55,25,22
10679,12071,0,4145,1,0,0,0,0,0,0,...,0,0,0,0,27,4,20,45,20,23
10680,180,0,7229,0,0,0,1,0,0,0,...,1,0,0,0,27,4,8,20,20,11
10681,12081,0,12648,0,0,0,0,0,0,0,...,0,0,0,1,1,3,11,30,10,14
10682,48161,2,11753,1,0,0,0,0,0,0,...,0,0,0,0,9,5,10,55,15,19

In [117]:
X = df.drop("Price",axis=1)

In [118]:
X

,Duration,Total_Stops,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,Airline_SpiceJet,...,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,Journey_Day,Journey_Month,Dep_Hour,Dep_Minute,Arrival_Minute,Arrival_Hour
0,12101,0,0,0,1,0,0,0,0,0,...,0,0,0,1,24,3,22,20,10,1
1,42176,2,1,0,0,0,0,0,0,0,...,0,0,0,0,1,5,5,50,15,13
2,1140,2,0,0,0,1,0,0,0,0,...,0,0,0,0,9,6,9,25,25,4
3,30126,1,0,0,1,0,0,0,0,0,...,0,0,0,0,12,5,18,5,30,23
4,24181,1,0,0,1,0,0,0,0,0,...,0,0,0,1,1,3,16,50,35,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,12061,0,0,0,0,0,0,0,0,0,...,0,0,0,0,9,4,19,55,25,22
10679,12071,0,1,0,0,0,0,0,0,0,...,0,0,0,0,27,4,20,45,20,23
10680,180,0,0,0,0,1,0,0,0,0,...,1,0,0,0,27,4,8,20,20,11
10681,12081,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,3,11,30,10,14
10682,48161,2,1,0,0,0,0,0,0,0,...,0,0,0,0,9,5,10,55,15,19

In [115]:
y = df["Price"]

In [116]:
y

0         3897
1         7662
2        13882
3         6218
4        13302
         ...
10678     4107
10679     4145
10680     7229
10681    12648
10682    11753
Name: Price, Length: 10682, dtype: int64

## TASK 2 — BUILD ML MODELS

Now we train models.

In [123]:
from sklearn.model_selection import train_test_split

Split Data

In [125]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=55)

#### Import Models

In [143]:
from sklearn.linear_model import LinearRegression,BayesianRidge
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

#### Evaluation Function

Train Multiple Models

In [146]:
model = {
    "Linearregression":LinearRegression(),
    "svm":SVR(),
    "DecisionTree":DecisionTreeRegressor(),
    "RandomForest":RandomForestRegressor(),
    "GradientBoosting":GradientBoostingRegressor(),
    "BayesianRidge":BayesianRidge()
}

result=[]
for name,model in model.items():
    model.fit(X_train,y_train)
    y_predict = model.predict(X_test)
    msr = mean_squared_error(y_test,y_predict)
    r2_val = r2_score(y_test,y_predict)
    result.append((name,r2_val,msr))

result

[('Linearregression', 0.5921341588697115, 9191059.358283903),
 ('svm', 0.09096393929291346, 20484687.733657215),
 ('DecisionTree', 0.6733542577521114, 7360803.733431602),
 ('RandomForest', 0.7904239976028116, 4722693.797466351),
 ('GradientBoosting', 0.7137784769957758, 6449863.514581267),
 ('BayesianRidge', 0.5923451614878632, 9186304.516390767)]

In [150]:
column = ["name","r2_score","mean_square_error"]

In [151]:
result_df = pd.DataFrame(result,columns = column)

##  MODEL COMPARISON REPORT

In [152]:
result_df

               name  r2_score  mean_square_error
0  Linearregression  0.592134       9.191059e+06
1               svm  0.090964       2.048469e+07
2      DecisionTree  0.673354       7.360804e+06
3      RandomForest  0.790424       4.722694e+06
4  GradientBoosting  0.713778       6.449864e+06
5     BayesianRidge  0.592345       9.186305e+06

### Best Model Conclusion

Random Forest Regressor is best model

#### Reasons:

- Captures non-linear relationships

- Handles categorical dummy variables well

- High R² score (~79%)

- Low error values

## CHALLENGES FACED REPORT


### 1️⃣ Data Cleaning Challenges

Missing values in Route & Total Stops

Solved by dropping rows.

### 2️⃣ Feature Engineering Complexity

Date, Time and Duration were in text format.

Converted to numerical features manually.

### 3️⃣ Categorical Variables

Airline, Source, Destination were text.

Solved using One-Hot Encoding.

### 4️⃣ Duration Conversion Issue

Duration was in "2h 50m" format.

Created custom function to convert into minutes.

### 5️⃣ Model Selection

Linear models underperformed due to non-linear data.

Ensemble models performed best.

# ----------------------------THANK YOU-------------------------------------